### ISSUE TITLE
Incorrect crafting recipe results and block drop quantities

### ISSUE THREAD

**Issue by LilCubo** [uItimatech/BountifulBlocks#2] opened 2024-08-28 08:49 UTC
Crafting recipes which should produce two or more resultant items (i.e. stairs or slabs) only produce one.
Stonecutter recipes which should produce two produce two or more resultant items (i.e. slabs) only produce one.
Double slab blocks drop one slab instead of two when mined.

![brick](https://github.com/user-attachments/assets/1e981d57-ecef-49b0-8814-e9157df43a60)
Crafting bricks produces 1 instead of 4
![slab](https://github.com/user-attachments/assets/956d1279-5faa-4d8f-997c-94ff0beba02a)
Crafting slabs produces 1 instead of 6
![stair](https://github.com/user-attachments/assets/46144e9f-a69d-4025-9d2e-a0285dd59fbf)
Crafting stair produces 1 instead of 4
![wall](https://github.com/user-attachments/assets/080ee453-53d1-489e-881f-4df3c5bde1ed)
Crafting walls produces 1 instead of 6
![stoneslab](https://github.com/user-attachments/assets/04077531-4bef-404e-bbed-537032b7c46f)
Stonecutting slabs produces 1 instead of 2

**Comment by uItimatech** [comment] 2024-08-28 19:58
Oh dang I remember the amounts were properly generated at some point. Will be fixed in the next update for all versions. Thanks for sharing.

**Comment by uItimatech** [comment] 2024-08-29 16:47
Ok, it was caused by the recipe updater script for 1.21. Will push update soon, it will also feature other bugfixes and reworked textures.

**Closed as completed** 2024-08-29 17:25 UTC
Labels: bug, fixed
